name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Docker Buildx (optional but recommended for better build performance)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.Docker File }}
          password: ${{ secrets.Docker File }}

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.Docker File }}/react-simple-app:latest .
          docker tag ${{ secrets.Docker File }}/react-simple-app:latest ${{ secrets.Docker File }}/react-simple-app:ROM

      # Push the Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.Docker File }}/react-simple-app:latest
          docker push ${{ secrets.Docker File }}/react-simple-app:ROM
